Initializes daft-sql and defines the daft.sql(..) function.
Eventual-Inc/Daft pull request #2559
Opened 2024-07-24 23:05 UTC by RCHowell

This pull request adds the daft-sql module to the Rust side, and defines a `daft.sql(..)` method along with a placeholder test.

Then intention of this PR is to establish the structure and plumbing before introducing any functionality.

2024-07-24 23:39 UTC, RCHowell commented
@universalmind303 sqlparser is bringing in arrow, how do you advise I resolve this to mitigate your concerns?

> we can't pull in any datafusion crates without pulling in multiple heavy dependencies such as [arrow-rs](https://crates.io/crates/arrow)

2024-07-25 16:33 UTC, RCHowell commented
## Demo

![demo](https://i.imgur.com/ik2Oahx.gif)

```python
import daft
from daft.sql.sql import SQLCatalog

# register dataframes to the catalog
catalog = SQLCatalog({
  "example": daft.from_pydict({ "a": [1, 2, 3] }),

})

# invoke daft.sql()
df = daft.sql("SELECT * FROM example", catalog)
df.collect()
```

2024-07-25 18:50 UTC, universalmind303 commented
so i think the work that I did in https://github.com/Eventual-Inc/Daft/pull/2558 will compliment this pretty well. 

#2558 adds a lot of sql parsing logic, and this PR sets up a lot of the python frontend that #2558 is missing.

2024-07-25 18:50 UTC, universalmind303 approved these changes
so i think the work that I did in https://github.com/Eventual-Inc/Daft/pull/2558 will compliment this pretty well. 

#2558 adds a lot of sql parsing logic, and this PR sets up a lot of the python frontend that #2558 is missing.

2024-07-25 18:57 UTC, RCHowell commented
Nice! I saw that we started to overlap on the Rust side — you were able to get a lot done so quickly. If you want to focus on the Rust side, I will rebase from #2558 when I have bandwidth.

2024-07-25 18:57 UTC, universalmind303 commented
> Nice! I saw that we started to overlap on the Rust side — you were able to get a lot done so quickly. If you want to focus on the Rust side, I will rebase from #2558 when I have bandwidth.

@RCHowell no need, we can merge this in first and I can rebase off of yours.

2024-07-25 18:59 UTC, universalmind303 commented on tests/sql/test_sql.py
> +from daft.sql.sql import SQLCatalog
nit: is there any way we can have this just `from daft.sql`  instead of `from daft.sql.sql

2024-07-25 18:59 UTC, universalmind303 commented on daft/sql/sql.py
> +    """SQLCatalog is a simple map from table names to dataframes used in query planning."""
let's add an `EXPERIMENTAL` warning to this one too.

2024-07-25 19:03 UTC, universalmind303 commented on daft/io/_sql.py
> +    print("Executing SQL query: ", sql)
remove `print`

2024-07-25 19:04 UTC, universalmind303 requested changes
a few small nits, but overall looks good! great work @RCHowell!

2024-07-25 21:05 UTC, universalmind303 approved these changes

2024-07-25 21:05 UTC, merged