[FEAT] Add a `list.contains` API
Eventual-Inc/Daft pull request #2773
Opened 2024-08-31 01:13 UTC by raunakab

# Overview
Added a `list.contains` API to check whether or not a column of type `List` or `FixedSizeList` contains a given value.

2024-09-16 22:08 UTC, kevinzwang requested changes
An alternative way to write the kernel is to check equality between the flattened list and the values and then for each list range, determine if there are any true values in that equality array. The potential advantage of this is that you can use the [vectorized arrow2 equality op](https://docs.rs/arrow2/latest/arrow2/compute/comparison/fn.eq.html). The potential disadvantage is that you can't early terminate if you find an equal value in a list. 

Also, please add tests!

2024-09-16 22:08 UTC, kevinzwang commented on src/daft-functions/src/list/contains.rs
> +                    DataType::List(inner_type) => {
Another check you should do with `inner_type` is to check if it is a type that you can check equality with the values.

2024-09-16 22:09 UTC, kevinzwang commented on src/daft-functions/src/list/contains.rs
> +                    DataType::List(inner_type) => {
Also, the dtype can be a `FixedSizeList`

2024-10-30 23:18 UTC, samster25 commented
@raunakab @kevinzwang status on this PR?

2024-11-21 00:59 UTC, raunakab commented on daft/expressions/expressions.py
> +            value (DataType): the value to search for in the list
Updated!

2024-11-21 01:00 UTC, raunakab commented on src/daft-core/src/array/ops/list.rs
> +        assert_eq!(self.len(), values.len(), "Expected two lists with the same length, instead got self.len() = {} and values.len() = {}", self.len(), values.len());
Updated.

2024-11-21 01:01 UTC, raunakab commented on daft/expressions/expressions.py
> +        return Expression._from_pyexpr(native.list_contains(self._expr, value._expr))
How about `self` then?

2024-11-21 01:04 UTC, kevinzwang commented on daft/expressions/expressions.py
> +        return Expression._from_pyexpr(native.list_contains(self._expr, value._expr))
Self is already an expression so there's no need. It should look something like
```py
value_expr = Expression.to_expression(value)
return Expression._from_pyexpr(native.list_contains(self._expr, value_expr._expr))
```

2024-11-21 08:09 UTC, raunakab commented on daft/expressions/expressions.py
> +        return Expression._from_pyexpr(native.list_contains(self._expr, value._expr))
Wait, I don't understand.

`value` is already of type `Expression`. `self` is of type `ExpressionListNamespace`. When I grab `self._expr` and `value._expr`, I am grabbing their internal `PyExpr` type, no? That is what the `native.list_contains` function expects.

2024-11-21 08:10 UTC, raunakab commented on daft/expressions/expressions.py
> +        return Expression._from_pyexpr(native.list_contains(self._expr, value._expr))
Why should we perform the `Expression._to_expression` conversion first? Looking at the implementation, it seems to take in a `object` and return the input if it is of type `Expression`.

2024-11-21 08:15 UTC, raunakab commented on daft/expressions/expressions.py
> +            Expression: a List expression which are the lists which all contain at least one instance of the given value.
I believe the original issue that @Vince7778 requested was to have the output be a column of lists in which each list contains the value that was being searched for in the first place.

The original issue gives a solid example, I believe.

2024-11-21 08:27 UTC, raunakab commented on daft/expressions/expressions.py
> +            Expression: a List expression which are the lists which all contain at least one instance of the given value.
I actually looked through my implementation. I implemented it incorrectly. Will update it.

2024-11-22 02:14 UTC, jaychia commented on daft/expressions/expressions.py
> +            Expression: a List expression which are the lists which all contain at least one instance of the given value.
Please take a closer look at the original issue.

1. The returned Expression is a boolean expression, indicating whether the list in each row contains the provided value
2. In the example provided, this boolean expression is then provided to a `df.where` which is performing the filtering.

There should be no concept of filtering at all in this PR. This is a simple scalar expression.

2024-12-03 16:32 UTC, raunakab commented
This is a stale PR. Closing in favour of https://github.com/Eventual-Inc/Daft/pull/3479.

2024-12-03 16:32 UTC, closed without merging