[FEAT] connect: `df.join`
Eventual-Inc/Daft pull request #3354
Opened 2024-11-20 09:12 UTC by andrewgazelka

2024-11-20 09:12 UTC, andrewgazelka commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3354?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3354** <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3354?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3354?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#3342** <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3342?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 7 other dependent PRs ([#3344](https://github.com/Eventual-Inc/Daft/pull/3344) <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3344?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>, [#3345](https://github.com/Eventual-Inc/Daft/pull/3345) <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3345?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>, [#3348](https://github.com/Eventual-Inc/Daft/pull/3348) <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3348?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> and 4 others)
* **#3343** <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3343?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 2 other dependent PRs ([#3309](https://github.com/Eventual-Inc/Daft/pull/3309) <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3309?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>, [#3326](https://github.com/Eventual-Inc/Daft/pull/3326) <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3326?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#3341** <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3341?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-21 15:47 UTC, universalmind303 requested changes

2024-11-21 15:47 UTC, universalmind303 commented on src/daft-connect/src/translation/logical_plan/join.rs
> +        false, // todo(correctness): we want join keys or not
I'm not sure what spark expects here. Usually SQL will retain the join keys, and most dataframes will not. I'd try to perform a simple join with spark and see what happens.

2024-11-21 15:47 UTC, universalmind303 commented on src/daft-connect/src/translation/logical_plan/join.rs
> +    }
we should definitely support both `USING` and regular joins. They are mutually exclusive though, so we'll need to error if both are provided

2024-11-21 15:47 UTC, universalmind303 commented on src/daft-connect/src/translation/logical_plan/join.rs
> +    if let Some(join_condition) = join_condition {
so we'll need some complicated logic to split the join condition into left and right halves. Check out the SQL frontend. We're doing something similar to split the join condition

2024-11-21 15:47 UTC, universalmind303 commented on tests/connect/test_join.py
> +    assert set(right_joined_pandas["id"].tolist()) == {3, 4, 5, 6}, "Right join should keep all rows from right DataFrame"
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines +6 to +28]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->we're going to need a lot more tests for joins. Check out the other join tests, both for dataframe and sql. <!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/Eventual-Inc/Daft/3354?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-11-21 15:47 UTC, universalmind303 commented on src/daft-connect/src/translation/logical_plan/join.rs
> +        JoinType::FullOuter => {
`FullOuter` is just the same as `Outer`

2024-11-21 15:47 UTC, universalmind303 commented on src/daft-connect/src/translation/logical_plan/join.rs
> +        JoinType::LeftAnti => Ok(daft_core::join::JoinType::Anti), // todo(correctness): is this correct?
remove comment. This is correct

2024-11-21 15:47 UTC, universalmind303 commented on src/daft-connect/src/translation/logical_plan/join.rs
> +        JoinType::LeftOuter => Ok(daft_core::join::JoinType::Left), // todo(correctness): is this correct?
remove comment. this is correct

2024-11-21 15:47 UTC, universalmind303 commented on src/daft-connect/src/translation/logical_plan/join.rs
> +        None,
does spark suffix/prefix the duplicate join keys at all? We should verify and match what they do here.

2024-11-22 22:10 UTC, universalmind303 commented on tests/connect/test_join.py
> +def test_cross_join(spark_session):
we don't support cross joins yet

2025-01-14 21:07 UTC, closed without merging